# Generated by Django 4.2.30 on 2026-06-28 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('approve_listing', 'Approve Listing'), ('reject_listing', 'Reject Listing'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('resolve_report', 'Resolve Fraud Report'), ('verify_transaction', 'Verify Transaction')], max_length=30)),
                ('target_id', models.UUIDField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'admin_actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
