# Generated by Django 4.2.30 on 2026-06-28 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaction',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['action_type'], name='admin_actio_action__d7b108_idx'),
        ),
        migrations.AddIndex(
            model_name='adminaction',
            index=models.Index(fields=['target_id'], name='admin_actio_target__e2db52_idx'),
        ),
    ]
