# Generated by Django 4.2.30 on 2026-06-28 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings_count', models.PositiveIntegerField(default=0)),
                ('completed_transactions_count', models.PositiveIntegerField(default=0)),
                ('is_trusted_seller', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reputation_scores',
                'ordering': ['-updated_at'],
            },
        ),
    ]
