# Generated by Django 4.2.30 on 2026-06-28 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('fraud_scam', 'Scam/Fraudulent Activity'), ('inappropriate_content', 'Inappropriate Content'), ('counterfeit', 'Counterfeit/Fake Product'), ('spam', 'Spam'), ('other', 'Other Policy Violation')], max_length=30)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reported_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against_listing', to='listings.listing')),
            ],
            options={
                'db_table': 'fraud_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
