# Generated by Django 4.2.30 on 2026-06-28 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudreport',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='fraudreport',
            constraint=models.CheckConstraint(check=models.Q(('reported_user__isnull', False), ('reported_listing__isnull', False), ('reported_transaction__isnull', False), _connector='OR'), name='fraud_report_requires_target'),
        ),
    ]
